=== irenerodriguezrod/DAW16/116LMSGIProyectoLMSGI/unidad4/02.2/02.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<!--Declaracion tipos simples-->

<!--Declaracion tipos complejos-->

<!--libro(titulo,autor,anio)-->
<xs:complexType name="tipoLibro">
<xs:sequence>
    <xs:element name="titulo" type="xs:string"/>
    <xs:element name="autor" type="tipoAutores"/>
    <xs:element name="anio" type="xs:gYear"/> <!--gYear solo almacena el a침o-->
</xs:sequence>

<!-- libro 
     id ID #REQUIRED 
     genero CDATA #IMPLIED 
     idioma CDATA "Espa침ol" 
     formato (impreso | digital) "impreso" 
     referencia IDREF #IMPLIED 
-->
<xs:attribute name="id" type="xs:ID" use="required"/>
<xs:attribute name="genero" type="xs:string" use="optional"/> <!-- pq es cdata-->
<xs:attribute name="idioma" type="xs:string" default="Espa침ol"/>
<xs:attribute name="formato" default="impreso">
    <xs:simpleType>
        <xs:restriction base="xs:string">
            <xs:enumeration value="impreso"/>
            <xs:enumeration value="digital"/>
        </xs:restriction>
    </xs:simpleType>
</xs:attribute>
<xs:attribute name="referencia" type="xs:IDREF" use="optional"/>
</xs:complexType>

<!-- autores(autor+)-->
<xs:complexType name="tipoAutores">
<xs:sequence>
    <xs:element name="autor" type="tipoAutor" maxOccurs="unbounded"/>
</xs:sequence>
</xs:complexType>

<!-- autor (nombre, apellido, nacionalidad?) -->
<xs:complexType name="tipoAutor">
<xs:sequence>
    <xs:element name="nombre" type="xs:string"/>
    <xs:element name="apellido" type="xs:string"/>
    <xs:element name="nacionalidad" type="xs:string" minOccurs="0"/> <!--Los valores con interrogacion son s칩lo 0 o 1-->
</xs:sequence>
</xs:complexType>

<!--Declaracion de elementos-->
<!--Declaracion del esquema-->
    <xs:element name="biblioteca">
        <xs:complexType>
        <xs:sequence>
            <xs:element name="libro" type="tipoLibro" maxOccurs="unbounded"/> <!--Unbounded significa que ese elemento se va a repetir-->
        </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== irenerodriguezrod/DAW16/116LMSGIProyectoLMSGI/unidad4/02.2/02.xml
<?xml version="1.0" encoding="UTF-8"?> 

<!-- 
     Nombre: Irene Rodríguez Rodríguez
     Descripción: Modificación de la tarea 2 de la unidad 4. Creación de los siguientes archivos: .dtd , .xml y .xsd
     Fecha de creación: 12/01/2025
     Fecha de modificación: 12/01/2025
-->

<!DOCTYPE biblioteca SYSTEM "02.dtd"> 

<biblioteca xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="02.xsd"> 

 <libro id="libro1" genero="novela" idioma="Inglés" formato="digital"> 
 <titulo>1984</titulo> 
 <autores> 
 <autor> 
 <nombre>George </nombre> 

 <apellido>Orwell</apellido> 

 <nacionalidad>Británica</nacionalidad> 

 </autor> 

 </autores> 
 <anio>1949</anio> 
 </libro> 

<libro id="libro2" genero="ciencia ficción" formato="impreso" referencia="libro1"> 
<titulo>Dune</titulo> 
<autores>
    <autor> 
        <nombre>Frank</nombre> 
        <apellido>Herbert</apellido> 
        <nacionalidad>Estadounidense</nacionalidad> 
    </autor> 
</autores> 
<anio>1965</anio> 
</libro> 

</biblioteca>
